# Generated by Django 4.1.7 on 2023-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_animals_alter_age_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default=1, help_text='Enter the composition of the product', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Enter a description of the product', max_length=500),
        ),
    ]
