# Generated by Django 4.1.7 on 2023-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_ingredients_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Enter the composition of the product', max_length=500, null=True),
        ),
    ]
