# Generated by Django 4.1.7 on 2023-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image-placeholder.jpeg', upload_to='product/'),
        ),
    ]
