# Generated by Django 4.1.7 on 2023-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image-placeholder.png', upload_to='product/'),
        ),
    ]
