# Generated by Django 4.1.7 on 2023-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='photo_2023-03-26_21-46-14.jpg', upload_to='product/'),
        ),
    ]
